import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const currentDir = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(resolve(currentDir, '../src/objects/ObjectDetailPage.tsx'), 'utf8');
const styles = readFileSync(resolve(currentDir, '../src/styles.css'), 'utf8');

test('object detail page loads active feed units with public filters', () => {
  assert.match(source, /FeedUnitsResponse/);
  assert.match(source, /const publicFeedUnitStatuses: FeedUnitStatus\[\] = \[\s*'AVAILABLE',\s*'BOOKED',\s*'RESERVED',\s*\];/);
  assert.match(source, /params\.set\('status', publicFeedUnitStatuses\.join\(','\)\);/);
  assert.match(source, /apiRequest<FeedUnitsResponse>\(`\/objects\/\$\{object\.id\}\/feed-units\?\$\{params\.toString\(\)\}`/);
  assert.match(source, /aria-label="Фильтр лотов по статусу"/);
  assert.match(source, /aria-label="Фильтр лотов по типу"/);
  assert.match(source, /feedUnitStatusFilterOptions/);
  assert.match(source, /AVAILABLE: 'Доступен'/);
  assert.match(source, /RESERVED: 'Резерв'/);
  assert.doesNotMatch(source, /feedUnitStatusFilterOptions[\s\S]*?ARCHIVED/);
});

test('object detail feed units block renders expected columns and media thumbnails', () => {
  assert.match(source, /<section className="detail-section object-feed-units-section"/);
  assert.match(source, /id="object-feed-units-title">Лоты<\/h3>/);
  assert.match(source, /<TableHead>Медиа<\/TableHead>/);
  assert.doesNotMatch(source, /<span>ID \{unit\.externalId\}<\/span>/);
  assert.doesNotMatch(source, /<strong>\{unit\.title \|\| unit\.externalId\}<\/strong>/);
  assert.match(source, /function getFeedUnitTitle\(unit: FeedUnit\)/);
  assert.match(source, /className="object-feed-media-button"/);
  assert.match(source, /type="button"[\s\S]*?onClick=\{\(\) => onOpenMedia\(unit\)\}/);
  assert.match(source, /<SecureImage[\s\S]*?className="object-feed-media-image"[\s\S]*?fileId=\{primaryMedia\.file\.id\}[\s\S]*?variant="thumbnail"/);
  assert.match(source, /Лоты не найдены/);
  assert.match(source, /Загрузка лотов/);
  assert.match(source, /Не удалось загрузить лоты/);

  assert.match(styles, /\.object-feed-units-section\s*\{/);
  assert.match(styles, /\.object-feed-units-toolbar\s*\{/);
  assert.match(styles, /\.object-feed-media-button\s*\{/);
  assert.match(styles, /\.object-feed-media-button:hover\s+\.object-feed-media-preview/);
  assert.match(styles, /\.object-feed-media-button:focus-visible\s*\{/);
  assert.match(styles, /\.object-feed-media-preview\s*\{/);
  assert.match(styles, /\.object-feed-units-table\s*\{/);
});

test('object detail feed units support server sorting from sortable headers', () => {
  assert.match(source, /type ObjectFeedUnitSortBy = 'title' \| 'status' \| 'price' \| 'area' \| 'rooms' \| 'floor' \| 'building';/);
  assert.match(source, /type ObjectFeedUnitSortDirection = 'asc' \| 'desc';/);
  assert.match(source, /const \[sortBy,\s*setSortBy\] = useState<ObjectFeedUnitSortBy>\('price'\);/);
  assert.match(source, /const \[sortDirection,\s*setSortDirection\] = useState<ObjectFeedUnitSortDirection>\('asc'\);/);
  assert.match(source, /params\.set\('sortBy', sortBy\);/);
  assert.match(source, /params\.set\('sortDirection', sortDirection\);/);
  assert.match(source, /function handleSort\(field: ObjectFeedUnitSortBy\)/);
  assert.match(source, /const nextDirection: ObjectFeedUnitSortDirection = sortBy === field && sortDirection === 'desc' \? 'asc' : 'desc';/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="title"[\s\S]*?>\s*Лот\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="status"[\s\S]*?>\s*Статус\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="price"[\s\S]*?>\s*Цена\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="area"[\s\S]*?>\s*Площадь\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="rooms"[\s\S]*?>\s*Комнаты\/тип\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="floor"[\s\S]*?>\s*Этаж\s*<\/ObjectFeedSortableHead>/);
  assert.match(source, /<ObjectFeedSortableHead[\s\S]*?field="building"[\s\S]*?>\s*Корпус\/секция\s*<\/ObjectFeedSortableHead>/);
  assert.match(styles, /\.object-feed-sort-button\s*\{/);
  assert.match(styles, /\.object-feed-sort-button\.is-active\s*\{/);
});

test('object detail feed unit sorting keeps existing rows visible while reloading', () => {
  assert.match(source, /const showFeedUnitsSkeleton = isLoading && units\.length === 0;/);
  assert.match(source, /const sortedUnits = useMemo\(/);
  assert.match(source, /sortFeedUnitsForDisplay\(units, sortBy, sortDirection\)/);
  assert.match(source, /\{showFeedUnitsSkeleton \? <ObjectFeedUnitsTableSkeleton \/> : null\}/);
  assert.match(source, /!\s*error[\s\S]*?\? sortedUnits\.map\(\(unit\) =>/);
  assert.doesNotMatch(source, /isLoading \? <ObjectFeedUnitsTableSkeleton \/> : null/);
  assert.doesNotMatch(source, /!isLoading && !error[\s\S]*?\? units\.map\(\(unit\) =>/);
});

test('object detail feed media opens lot files in a carousel with fullscreen preview', () => {
  assert.match(source, /const \[mediaCarouselUnit,\s*setMediaCarouselUnit\] = useState<FeedUnit \| null>\(null\);/);
  assert.match(source, /<ObjectFeedMediaCarousel[\s\S]*?accessToken=\{accessToken\}[\s\S]*?unit=\{mediaCarouselUnit\}[\s\S]*?onClose=\{\(\) => setMediaCarouselUnit\(null\)\}/);
  assert.match(source, /function ObjectFeedMediaCarousel/);
  assert.match(source, /const \[activeIndex,\s*setActiveIndex\] = useState\(0\);/);
  assert.match(source, /const \[fullscreenMedia,\s*setFullscreenMedia\] = useState<FeedUnit\['media'\]\[number\] \| null>\(null\);/);
  assert.match(source, /className="object-feed-media-carousel"/);
  assert.match(source, /className="object-feed-media-carousel-stage"/);
  assert.match(source, /className="object-feed-media-carousel-image-button"/);
  assert.match(source, /onClick=\{\(\) => setFullscreenMedia\(activeMedia\)\}/);
  assert.match(source, /className="object-feed-media-fullscreen"/);
  assert.match(source, /className="object-feed-media-carousel-image"[\s\S]*?variant="original"/);
  assert.match(source, /className="object-feed-media-fullscreen-image"[\s\S]*?variant="original"/);
  assert.match(source, /unit\.media\.map\(\(media\) =>/);
  assert.match(source, /href=\{buildMediaFileContentUrl\(fullscreenMedia\.file\.id\)\}/);
  assert.doesNotMatch(source, /function ObjectFeedMediaModal/);
  assert.doesNotMatch(source, /object-feed-media-modal/);
  assert.match(styles, /\.object-feed-media-carousel-backdrop\s*\{/);
  assert.match(styles, /\.object-feed-media-carousel-thumbs\s*\{/);
  const carouselBlock = styles.match(/\.object-feed-media-carousel\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(carouselBlock, /width:\s*min\(1040px,\s*calc\(100vw - 48px\)\);/);
  assert.match(carouselBlock, /height:\s*min\(820px,\s*calc\(100dvh - 48px\)\);/);
  assert.match(carouselBlock, /overflow:\s*hidden;/);
  const carouselStageBlock = styles.match(/\.object-feed-media-carousel-stage\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(carouselStageBlock, /height:\s*100%;/);
  assert.match(carouselStageBlock, /min-height:\s*0;/);
  assert.match(carouselStageBlock, /overflow:\s*hidden;/);
  const imageButtonBlock = styles.match(/\.object-feed-media-carousel-image-button\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(imageButtonBlock, /position:\s*relative;/);
  assert.match(imageButtonBlock, /\n\s*width:\s*100%;/);
  assert.match(imageButtonBlock, /max-width:\s*860px;/);
  assert.match(imageButtonBlock, /\n\s*height:\s*100%;/);
  assert.match(imageButtonBlock, /max-height:\s*100%;/);
  assert.match(imageButtonBlock, /min-width:\s*0;/);
  assert.match(imageButtonBlock, /min-height:\s*0;/);
  assert.match(imageButtonBlock, /overflow:\s*hidden;/);
  const carouselImageBlock = styles.match(/\.object-feed-media-carousel-image\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(carouselImageBlock, /position:\s*absolute;/);
  assert.match(carouselImageBlock, /inset:\s*0;/);
  assert.match(carouselImageBlock, /\n\s*width:\s*100%;/);
  assert.match(carouselImageBlock, /\n\s*height:\s*100%;/);
  assert.match(carouselImageBlock, /object-fit:\s*contain;/);
  const carouselThumbBlock = styles.match(/\.object-feed-media-carousel-thumb\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(carouselThumbBlock, /position:\s*relative;/);
  const carouselThumbImageBlock = styles.match(/\.object-feed-media-carousel-thumb-image\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(carouselThumbImageBlock, /position:\s*absolute;/);
  assert.match(carouselThumbImageBlock, /inset:\s*0;/);
  assert.match(carouselThumbImageBlock, /object-fit:\s*contain;/);
  const fullscreenBlock = styles.match(/\.object-feed-media-fullscreen\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(fullscreenBlock, /overflow:\s*hidden;/);
  const fullscreenImageButtonBlock = styles.match(/\.object-feed-media-fullscreen-image-button\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(fullscreenImageButtonBlock, /position:\s*relative;/);
  assert.match(fullscreenImageButtonBlock, /min-width:\s*0;/);
  assert.match(fullscreenImageButtonBlock, /min-height:\s*0;/);
  assert.match(fullscreenImageButtonBlock, /overflow:\s*hidden;/);
  const fullscreenImageBlock = styles.match(/\.object-feed-media-fullscreen-image\s*\{[^}]*\}/)?.[0] ?? '';
  assert.match(fullscreenImageBlock, /position:\s*absolute;/);
  assert.match(fullscreenImageBlock, /inset:\s*0;/);
  assert.match(fullscreenImageBlock, /\n\s*width:\s*100%;/);
  assert.match(fullscreenImageBlock, /\n\s*height:\s*100%;/);
  assert.match(fullscreenImageBlock, /max-width:\s*100%;/);
  assert.match(fullscreenImageBlock, /max-height:\s*100%;/);
  assert.match(fullscreenImageBlock, /object-fit:\s*contain;/);
  assert.doesNotMatch(styles, /\.object-feed-media-modal\s*\{/);
});
